block-blacklist:
  - "KELP"
  - "KELP_PLANT"
  - "GRASS"
  - "SEAGRASS"
  - "TALL_SEAGRASS"
  - "DANDELION"
  - "POPPY"
  - "BLUE_ORCHID"
  - "ALLIUM"
  - "AZURE_BLUET"
  - "RED_TULIP"
  - "ORANGE_TULIP"
  - "WHITE_TULIP"
  - "PINK_TULIP"
  - "OXEYE_DAISY"
  - "CORNFLOWER"
  - "LILY_OF_THE_VALLEY"
  - "TORCHFLOWER"
  - "PINK_PETALS"
  - "SPORE_BLOSSOM"
  - "ROSE_BUSH"
  - "GRASS"
  - "SAND"
  - "FIRE"
  - "SUGAR_CANE"
  - "COAL_ORE"
  - "IRON_ORE"
  - "COPPER_ORE"
  - "GOLD_ORE"
  - "REDSTONE_ORE"
  - "EMERALD_ORE"
  - "LAPIS_ORE"
  - "DIAMOND_ORE"
  - "DEEPSLATE_COPPER_ORE"
  - "DEEPSLATE_GOLD_ORE"
  - "DEEPSLATE_REDSTONE_ORE"
  - "DEEPSLATE_EMERALD_ORE"
  - "DEEPSLATE_LAPIS_ORE"
  - "DEEPSLATE_DIAMOND_ORE"
  - "OAK_LOG"
  - "SPRUCE_LOG"
  - "BIRCH_LOG"
  - "JUNGLE_LOG"
  - "ACACIA_LOG"
  - "DARK_OAK_LOG"
  - "OBSIDIAN"
  - "TALL_GRASS"

update-interval: 20
world-blacklist:
  - world_nether
  - world_the_end



database:
  type: mysql # または 'sqlite' <-ここを変更してください。


