name: Digger
version: '${project.version}'
main: net.hotamachisubaru.digger.Digger
api-version: '1.20'
load: STARTUP
author:
  Copyright (c) 2023-2025 ほたまちスバル
commands:
  reload:
    description: 設定を再読み込みします。
    usage: /reload
    permission: digger.reload
  set:
    description: 掘ったダイヤモンド数を強制的にセットします。
    usage: /set <value>
    permission: digger.set
permissions:
  digger.reload:
    description: 設定を再読み込みします。
    default: op
  digger.set:
    description: 掘ったダイヤモンド数を強制的にセットします。
    default: op